### PR TITLE
Update README + add support for .env files + add .gitignore + format …

### PR DESCRIPTION
**Pull request by Woetfin**
* Updated README documentation to give more setup details and explain how to run the commands as npm scripts
* Added support for .env files so we can define the environment variables per project in one time
* Added .gitignore to prevent secrets and installed dependencies tracking
* Formatted JS code with the 'Prettier' extension

### CODE REVIEW

**Comment by Woetfin** [comment]
@TheSmartnik I've fixed the merge conflict that happened after the previous merge, would it be ok for you to add the dotenv dependency to support .env files or do you think this is not a good feature to add?

**Comment by TheSmartnik** [comment]
@Woetfin thanks! Everything looks good but good you please remove formatting changes? We'll add eslinter with silverfin config later on

**Comment by Woetfin** [comment]
@TheSmartnik I've removed the Prettier formatting from the files

**Comment by TheSmartnik** [comment]
@Woetfin thanks!

**Pull request merged**
